# Generated by Django 4.2 on 2025-11-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('veiculo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
            ],
        ),
    ]
