# Generated by Django 4.2 on 2025-11-28 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_servico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
