# Generated by Django 4.2 on 2025-11-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servico_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do serviço em R$', max_digits=10, null=True),
        ),
    ]
